# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Comprehensive combination of checks, linting, feature-checks, testing to be run on merge and on PR
# Upload test results for potential re-use in publication workflow, returns the corresponding download URL as an output on workflow_call

name: Cargo

on:
  push:
    branches: 
      - main
  pull_request:
    paths:
      - "examples/**"
      - "src/**"
      - "tests/**"
      - "Cargo.*"
  workflow_call:
    outputs:
      test_results_url:
        description: "URL of the test results artifact"
        value: ${{ jobs.nextest.outputs.test_results_url }}
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - uses: dtolnay/rust-toolchain@master
      with: 
        toolchain: ${{ env.RUST_TOOLCHAIN }}
    - name: Run cargo check
      run: |
        cargo check --workspace --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt
      - name: Run cargo fmt
        run: |
          cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - name: Run cargo clippy
        run: |
          cargo clippy --version
          cargo clippy --all-targets --all-features --no-deps -- -W warnings -D warnings

  docu:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Run rustdoc
        run: |
          cargo doc --no-deps --all-features

  feature-check:
    # Comprehensive check on dependencies for all feature flag combinations, excluding development dependencies
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - name: Run cargo hack powerset
        run: |
          cargo hack check --feature-powerset --no-dev-deps

  nextest:
    # Subset of feature-combos, on only one OS - more complete testing in test-featurematrix.yaml
    outputs:
      test_results_url: ${{ steps.test_results.outputs.artifact-url }}
    runs-on: ubuntu-latest
    env: 
      NEXTEST_EXPERIMENTAL_LIBTEST_JSON: 1
    strategy:
      matrix:
        feature-flags: ["", "--no-default-features", "--all-features"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@v2
      # install tool to convert cargo's JSON test output to JUNIT format
      - run: |
          cargo install cargo2junit
      # Using nextest because it's faster than built-in test
      - uses: taiki-e/install-action@nextest
      - name: Run cargo nextest
        run: |
          cargo nextest run ${{ matrix.feature-flags }} --profile ci
      - name: Run doctests
        run: |
          # we use tee to let cargo test print to the console
          RUSTC_BOOTSTRAP=1 cargo test --doc ${{ matrix.feature-flags }} -- -Z unstable-options --format json --report-time | tee target/doctest-results.json
          # write output to same directory as the one used by cargo nextest in order
          # to flatten the directory hierarchy when uploading the test results
          cat target/doctest-results.json | cargo2junit > target/nextest/ci/doctest-results.xml

      - name: Upload all-features test results artifact
        id: test_results
        if: matrix.feature-flags == '--all-features'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          # this will include the nextest and doctest result files in the archive's root folder
          path: target/nextest/ci/*-results.xml
